# Generated by Django 4.1.3 on 2022-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionNotas', '0002_post_delete_notasrapidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
