# Generated by Django 4.1.3 on 2022-12-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionNotas', '0008_alter_nota_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
