# Generated by Django 4.1.3 on 2022-12-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppGestionNotas', '0012_alter_nota_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernotas', to=settings.AUTH_USER_MODEL),
        ),
    ]
