# Generated by Django 4.1.3 on 2022-12-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionNotas', '0013_alter_nota_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
